# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureKeyVault@2
    displayName: Get secrets fromkey valut
    inputs:
      azureSubscription: 'AppKeyVault'
      KeyVaultName: 'TestKeyValut1988'
      SecretsFilter: '*'
      RunAsPreJob: true
  - task: CmdLine@2
    displayName: Write DbPwd into file
    inputs:
      script: |
        echo $(DbPwd)
        echo $(DbUser) > DbPwd.txt
  - task: CopyFiles@2
    inputs:
      Contents: DbPwd.txt
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  
  
